language: node_js
node_js:
  - 0.10
before_script:
  - export QINIU_ACCESS_KEY=QWYn5TFQsLLU1pL5MFEmX3s5DmHdUThav9WyOWOm
  - export QINIU_SECRET_KEY=Bxckh6FA-Fbs9Yt3i3cbKVK22UPBmAOHJcL95pGz
  - export QINIU_TEST_BUCKET="nodesdk"
  - export QINIU_TEST_DOMAIN="nodesdk.qiniudn.com"
